### ISSUE TITLE
Mis-reading flat files as science files

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#1]
[lr182@alice04 saao_scripts]$ python safphot.py -c SHA -d ../NG1421+0000_04553_all
Namespace(c=['SHA'], d=['../NG1421+0000_04553_all'])
Searching directory ../NG1421+0000_04553_all
37 files found.
Files sorted.
Found 1 bias files.
Found 0 flat files:
Found 36 target files:
	 31 files for target V_flat (V - Green).
	 5 files for target NG1421+0000_4553 (V - Green).
Traceback (most recent call last):
  File "safphot.py", line 41, in <module>
    files.summary_ra_dec()
AttributeError: fits_sort instance has no attribute 'summary_ra_dec'

**Comment by apchsh** [comment]
I've made changes to fix this. As long as the header "OBJECT" key word has the word flat in it somewhere it should recognise them correctly.
