### ISSUE TITLE
Flux output values 0/NAN after file 147

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#11]
If you look at the flux output for NG1421+0000_4553_all, after line 147 or so it's 0s or NANs?

**Comment by Lraynard** [comment]
I think this is connected to issue #9 as I didn't have that problem on other datasets

**Comment by apchsh** [comment]
I think this is something funny with that particular dataset. It sounds like a corrupted file to me?

**Comment by apchsh** [comment]
Closing for a corrupt file.
