### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '../NG1421+0000_04553_allreduction/'

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#3]
Reduction and unpacking complete.
Traceback (most recent call last):
  File "safphot.py", line 51, in <module>
    for item in os.listdir(dir_):
OSError: [Errno 2] No such file or directory: '../NG1421+0000_04553_allreduction/'

**Fixed by editing line of safphot.py58 **
 dir_ = os.path.join(args.d[0],'reduction/')

**Comment by apchsh** [comment]
Fixed thanks.
