### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#6]
This one might be because I accidentally ran it on the wrong directory which already had the reduction and calframes folders. In fact I'm sure it is

Creating calibration frames for data.
Default output dir is ../NG1421+0000_04553_all/calframes/
(50, 256, 256)
(256, 256)
Bias calibration frame saved to ../NG1421+0000_04553_all/calframes/bias.fits (50 exposures).
Normalised flat calibration frame saved to ../NG1421+0000_04553_all/calframes/flat_V_-_Green.fits (93         exposures)
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/SHA_20170708.0001.fits 
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 1.3 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/SHA_20170708.0002.fits 
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/SHA_20170708.0003.fits 
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/SHA_20170708.0004.fits 
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/SHA_20170708.0005.fits 
Processing NG1421+0000_4553 (V - Green): ../NG1421+0000_04553_all/reduction/NG1421+0000_4553_V_-_Green/SHA_20170708.0001.0000.fits 
Traceback (most recent call last):
  File "safphot.py", line 47, in <module>
    up.unpack_reduce(files, calframes, verbose=True)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/unpack.py", line 64, in unpack_reduce
    red_data = ( f[0].data[count, :, :] - calframes['bias'] ) / calframes[filt]
IndexError: too many indices for array

**Comment by apchsh** [comment]
Yep, I need to add code to check whether it has already been run on a dir and if so don't re-run on the reduced files!
